name: Unzip htck.zip to newweb folder

on:
  push:
    paths:
      - 'newweb/htck.zip'  # 监听你上传的 ZIP 文件路径，例如 'assets/htck.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest  # 在 Ubuntu 环境下运行

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Unzip htck.zip to the newweb folder
      - name: Unzip htck.zip
        run: |
          mkdir -p newweb  # 确保 newweb 文件夹存在
          unzip htck.zip -d newweb/  # 解压文件到 newweb 文件夹

      # Step 3: Add and commit the unzipped files
      - name: Add and commit the unzipped files
        run: |
          git add newweb/  # 将解压后的文件添加到暂存区
          git commit -m "Unzipped htck.zip to newweb folder"  # 提交更改
          git push  # 推送更改到 GitHub 仓库
