name: Unzip htck.zip to newweb folder

on:
  push:
    paths:
      - 'htck.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install unzip if not installed
        run: |
          if [[! $(command - v unzip) ]]; then
            sudo apt-get update
            sudo apt-get install -y unzip
          fi

      - name: Unzip htck.zip
        run: |
          mkdir -p newweb
          unzip -o htck.zip -d newweb/

      - name: Add and commit the unzipped files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add newweb/
          git commit -m "Unzipped htck.zip to newweb folder"
          git push
